services:
  postgres:
    image: postgres:15
    container_name: lol_postgres
    restart: always
    environment:
      POSTGRES_USER: lol_user
      POSTGRES_PASSWORD: lol_pass
      POSTGRES_DB: lol_db
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: lol_metabase
    ports:
      - "33000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    depends_on:
      - postgres

volumes:
  postgres_data: